
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JFrame; 
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class MAINMENU extends javax.swing.JFrame {

    // 1. NEW CLASS FIELDS: Store references for search and filtering
    private JPanel cardsContainer; 
    private List<CardPanel> cardList;

    public MAINMENU() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   {
       // Initialize the card list
        cardList = new ArrayList<>();
        
        // --- Frame Setup ---
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Main Menu (Search Enabled)");

        getContentPane().setLayout(new BorderLayout(10, 10)); 
        getContentPane().setBackground(new Color(230, 230, 230));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Main Menu");
        setMinimumSize(new Dimension(700, 600));

        // Set layout for JFrame
        getContentPane().setLayout(new BorderLayout(10, 10));
        getContentPane().setBackground(new Color(230, 230, 230));

        // --- A. Top Panel for Search Bar (NORTH) ---
        JPanel searchPanel = new JPanel();
        searchPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 10));
        searchPanel.setBackground(new Color(230, 230, 230));

       JTextField searchField = new JTextField(40);
        searchField.setPreferredSize(new Dimension(searchField.getPreferredSize().width, 35));
        searchField.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        
        searchField.getDocument().addDocumentListener(new SearchDocumentListener(searchField));
        
        JButton searchButton = new JButton("🔍"); 
        searchButton.setPreferredSize(new Dimension(40, 35));
        searchButton.setMargin(new Insets(0, 0, 0, 0));

        searchPanel.add(searchField);
        searchPanel.add(searchButton);
        getContentPane().add(searchPanel, BorderLayout.NORTH);

        // --- Main Content Panel for Cards ---
        cardsContainer = new JPanel();
        cardsContainer.setLayout(new BoxLayout(cardsContainer, BoxLayout.Y_AXIS));
        cardsContainer.setBackground(new Color(230, 230, 230)); 
        cardsContainer.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        
        String[] eventNames = {
            "Mr & Ms NBSC", "Bench Cheering Competition", 
            "Clean Up Drive", "Codathon 2025", 
            "Mobile Legends Tournament", "Earthquake Drill", 
            "Mr & Ms IT", "Mens Volleyball Competition",
            "Womens Volleyball Competition", "Mens Basketball Competition",
            "Womens Basketball Competition", "Dance Competition"
        };
        
        for (String name : eventNames) {
            CardPanel card = new CardPanel(name);
            cardList.add(card); // Add card to the list for searching
            cardsContainer.add(card);
            cardsContainer.add(Box.createVerticalStrut(10)); // Spacer
        }

        // --- Scroll Pane for Cards ---
       JScrollPane scrollPane = new JScrollPane(cardsContainer);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        scrollPane.setBorder(BorderFactory.createEmptyBorder());

        getContentPane().add(scrollPane, BorderLayout.CENTER);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        pack();
        setLocationRelativeTo(null); // Center the window
    }// </editor-fold>
    // 2. NEW INNER CLASS: Handles real-time search filtering
    private class SearchDocumentListener implements DocumentListener {
        private JTextField searchField;

        public SearchDocumentListener(JTextField searchField) {
            this.searchField = searchField;
        }

        private void filterCards() {
            String searchText = searchField.getText().toLowerCase();
            
            for (CardPanel card : cardList) {
                String eventName = card.getEventName().toLowerCase();
                
                // Check if the card's event name contains the search text
                boolean visible = eventName.contains(searchText);
                
                card.setVisible(visible);
                
                // This forces the container to re-layout, removing the blank space 
                // where the invisible cards used to be.
                cardsContainer.revalidate();
                cardsContainer.repaint();
            }
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            filterCards();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filterCards();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            // Not used for simple text fields
        }
    }
    // ------------------------------------------------------------------

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MAINMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAINMENU().setVisible(true);
            }
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

